spring.application.name=RAG
# Google GenAI - Chat
spring.ai.google.genai.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.project-id=${PROJECT_ID}
spring.ai.google.genai.chat.model=gemini-3.5-flash
spring.ai.google.genai.chat.max-output-tokens=2000

# Google GenAI - Embedding
spring.ai.google.genai.embedding.api-key=${GEMINI_API_KEY}
spring.ai.google.genai.embedding.project-id=${PROJECT_ID}
spring.ai.google.genai.embedding.text.options.model=gemini-embedding-001

# Explicit model selection
spring.ai.model.embedding.text=google-genai

tess4j.datapath=src/main/resources/tessdata
tess4j.language=eng